### ISSUE TITLE
Design Basic Types

### ISSUE THREAD

**Issue by SilasReinagel** [SilasReinagel/oo.core.dotnet#11]
I'm thinking the basic types (interfaces) are: Bytes, Text, Number, and Value<T>.

A couple of questions. Should we do WholeNumber and RealNumber, or just Number?

Also, do we want to follow the Printers, no Getters concept?

And what the right name for commands?
```var command = new LogThisText("My Text").Go()```
Is Go() the best verb?

Shall we make Text an abstract base class so that we can add implicit conversion from/to string?

**Comment by ZavixDragon** [comment]
The other basic type we will need is Flag, otherwise I like those (I have decided I can't think of a single use case where you would just need Char, even if you wanted to enforce a single character Text, you could just make an implementation of Text that did that)

We should just do Number, and RealNumber will be an implementation of Number

We should not enforce the printers no getters concept, as it becomes complicated when you have unhappy path possibilities.

I can't think of a better name than Go() for generic commands, it's intuitive

We have to be careful with an abstract class like Text, because people could very easily accidentally use a class as Text when they were not meaning to

**Comment by SilasReinagel** [comment]
Flag/Boolean does seem very important. What is the best human name for something like that?

WholeNumber can be a type of Number.

In what scenario would someone accidentally use Text without meaning to?

**Comment by SilasReinagel** [comment]
What about Condition instead of Boolean/Flag?

**Comment by ZavixDragon** [comment]
Condition is excellent name

**Comment by ZavixDragon** [comment]
I also think that number should not expose AsInt() upon reflecting you only use numbers with other numbers but right when you go to consume you either pull its value use it implicitly or you can do new FloorNumber(number).AsReal()

**Comment by SilasReinagel** [comment]
Another important basic type will be some sort of DateTime object.

**Comment by ZavixDragon** [comment]
some form of TimeSpan also seems important now that you mention it.

**Comment by SilasReinagel** [comment]
So, it seems clear that Number will require some more initial design.

Also, I think that `TimeSpan` and `DateTimeOffset` are good enough that we can use them as default types for now. Maybe add some smart objects as needed.

**Comment by ZavixDragon** [comment]
That sounds like a good idea, eventually we can build a smart object that hides the static functionality that exists in them
